### ISSUE TITLE
Github?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [pabloscloud/Overload#32]
Warum bist du jetzt gewechselt ? (auf mastodon hast du nicht geantwortet)

**Comment by pabloscloud** [comment]
GitHub is better for project management imho. If I continued to use Codeberg I would have needed to use another tool to track issues and I didn't see myself doing that :/

**Comment by pabloscloud** [comment]
And additionally I didn't get that your "note to self: I need to remove..." is a question haha
